routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('woocrack_plugins', 'Admin\WoocrackPluginsController');
    Route::post('woocrack_plugins_mass_destroy', ['uses' => 'Admin\WoocrackPluginsController@massDestroy', 'as' => 'woocrack_plugins.mass_destroy']);
    Route::post('woocrack_plugins_restore/{id}', ['uses' => 'Admin\WoocrackPluginsController@restore', 'as' => 'woocrack_plugins.restore']);
    Route::delete('woocrack_plugins_perma_del/{id}', ['uses' => 'Admin\WoocrackPluginsController@perma_del', 'as' => 'woocrack_plugins.perma_del']);
    Route::resource('woocrack_plugins_downloads', 'Admin\WoocrackPluginsDownloadsController');
    Route::post('woocrack_plugins_downloads_mass_destroy', ['uses' => 'Admin\WoocrackPluginsDownloadsController@massDestroy', 'as' => 'woocrack_plugins_downloads.mass_destroy']);
    Route::post('woocrack_plugins_downloads_restore/{id}', ['uses' => 'Admin\WoocrackPluginsDownloadsController@restore', 'as' => 'woocrack_plugins_downloads.restore']);
    Route::delete('woocrack_plugins_downloads_perma_del/{id}', ['uses' => 'Admin\WoocrackPluginsDownloadsController@perma_del', 'as' => 'woocrack_plugins_downloads.perma_del']);



 
});

app/WoocrackPlugin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class WoocrackPlugin
 *
 * @package App
 * @property string $url
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\WoocrackPluginsDownload[] $woocrack_plugins_downloads
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin newQuery()
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPlugin onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin whereCreatedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin whereDeletedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin whereId( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin whereUpdatedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPlugin whereUrl( $value )
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPlugin withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPlugin withoutTrashed()
 * @mixin \Eloquent
 */
class WoocrackPlugin extends Model {
    use SoftDeletes;

    protected $fillable = [ 'url', 'author_url' ];
    protected $hidden = [];


    public static function boot() {
        parent::boot();

        WoocrackPlugin::observe( new \App\Observers\UserActionsObserver );
    }

    public function woocrack_plugins_downloads() {
        return $this->hasMany( WoocrackPluginsDownload::class, 'plugin_url_id' );
    }
}

app/Http/Controllers/Admin/WoocrackPluginsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreWoocrackPluginsRequest;
use App\Http\Requests\Admin\UpdateWoocrackPluginsRequest;
use App\WoocrackPlugin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Yajra\DataTables\DataTables;

class WoocrackPluginsController extends Controller {
    /**
     * Display a listing of WoocrackPlugin.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if ( ! Gate::allows( 'woocrack_plugin_access' ) ) {
            return abort( 401 );
        }


        if ( request()->ajax() ) {
            $query    = WoocrackPlugin::query();
            $template = 'actionsTemplate';
            if ( request( 'show_deleted' ) == 1 ) {

                if ( ! Gate::allows( 'woocrack_plugin_delete' ) ) {
                    return abort( 401 );
                }
                $query->onlyTrashed();
                $template = 'restoreTemplate';
            }
            $query->select( [
                'woocrack_plugins.id',
                'woocrack_plugins.url',
                'woocrack_plugins.author_url',
            ] );
            $table = Datatables::of( $query );

            $table->setRowAttr( [
                'data-entry-id' => '{{$id}}',
            ] );
            $table->addColumn( 'massDelete', '&nbsp;' );
            $table->addColumn( 'actions', '&nbsp;' );
            $table->editColumn( 'actions', function ( $row ) use ( $template ) {
                $gateKey  = 'woocrack_plugin_';
                $routeKey = 'admin.woocrack_plugins';

                return view( $template, compact( 'row', 'gateKey', 'routeKey' ) );
            } );
            $table->editColumn( 'url', function ( $row ) {
                return $row->url ? $row->url : '';
            } );
            $table->editColumn( 'author_url', function ( $row ) {
                return $row->author_url ? '<a href="' . $row->author_url . '" target="_blank">' . $row->author_url . '</a>' : '';
            } );

            $table->rawColumns( [ 'actions', 'massDelete' ] );

            return $table->escapeColumns( [] )->make( true );
        }

        return view( 'admin.woocrack_plugins.index' );
    }

    /**
     * Show the form for creating new WoocrackPlugin.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        if ( ! Gate::allows( 'woocrack_plugin_create' ) ) {
            return abort( 401 );
        }

        return view( 'admin.woocrack_plugins.create' );
    }

    /**
     * Store a newly created WoocrackPlugin in storage.
     *
     * @param  \App\Http\Requests\StoreWoocrackPluginsRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store( StoreWoocrackPluginsRequest $request ) {
        if ( ! Gate::allows( 'woocrack_plugin_create' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::create( $request->all() );

        foreach ( $request->input( 'woocrack_plugins_downloads', [] ) as $data ) {
            $woocrack_plugin->woocrack_plugins_downloads()->create( $data );
        }


        return redirect()->route( 'admin.woocrack_plugins.index' );
    }


    /**
     * Show the form for editing WoocrackPlugin.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit( $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_edit' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::findOrFail( $id );

        return view( 'admin.woocrack_plugins.edit', compact( 'woocrack_plugin' ) );
    }

    /**
     * Update WoocrackPlugin in storage.
     *
     * @param  \App\Http\Requests\UpdateWoocrackPluginsRequest $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update( UpdateWoocrackPluginsRequest $request, $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_edit' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::findOrFail( $id );
        $woocrack_plugin->update( $request->all() );

        $woocrackPluginsDownloads           = $woocrack_plugin->woocrack_plugins_downloads;
        $currentWoocrackPluginsDownloadData = [];
        foreach ( $request->input( 'woocrack_plugins_downloads', [] ) as $index => $data ) {
            if ( is_integer( $index ) ) {
                $woocrack_plugin->woocrack_plugins_downloads()->create( $data );
            } else {
                $id                                        = explode( '-', $index )[1];
                $currentWoocrackPluginsDownloadData[ $id ] = $data;
            }
        }
        foreach ( $woocrackPluginsDownloads as $item ) {
            if ( isset( $currentWoocrackPluginsDownloadData[ $item->id ] ) ) {
                $item->update( $currentWoocrackPluginsDownloadData[ $item->id ] );
            } else {
                $item->delete();
            }
        }


        return redirect()->route( 'admin.woocrack_plugins.index' );
    }


    /**
     * Display WoocrackPlugin.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show( $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_view' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_downloads = \App\WoocrackPluginsDownload::where( 'plugin_url_id', $id )->get();

        $woocrack_plugin = WoocrackPlugin::findOrFail( $id );

        return view( 'admin.woocrack_plugins.show', compact( 'woocrack_plugin', 'woocrack_plugins_downloads' ) );
    }


    /**
     * Remove WoocrackPlugin from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::findOrFail( $id );
        $woocrack_plugin->delete();

        return redirect()->route( 'admin.woocrack_plugins.index' );
    }

    /**
     * Delete all selected WoocrackPlugin at once.
     *
     * @param Request $request
     */
    public function massDestroy( Request $request ) {
        if ( ! Gate::allows( 'woocrack_plugin_delete' ) ) {
            return abort( 401 );
        }
        if ( $request->input( 'ids' ) ) {
            $entries = WoocrackPlugin::whereIn( 'id', $request->input( 'ids' ) )->get();

            foreach ( $entries as $entry ) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore WoocrackPlugin from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function restore( $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::onlyTrashed()->findOrFail( $id );
        $woocrack_plugin->restore();

        return redirect()->route( 'admin.woocrack_plugins.index' );
    }

    /**
     * Permanently delete WoocrackPlugin from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function perma_del( $id ) {
        if ( ! Gate::allows( 'woocrack_plugin_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugin = WoocrackPlugin::onlyTrashed()->findOrFail( $id );
        $woocrack_plugin->forceDelete();

        return redirect()->route( 'admin.woocrack_plugins.index' );
    }
}

app/Http/Controllers/Api/V1/WoocrackPluginController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreWoocrackPluginsRequest;
use App\Http\Requests\API\StoreWoocrackPluginsRequest as API_StoreWoocrackPluginsRequest;
use App\Http\Resources\WoocrackPluginResource;
use App\WoocrackPlugin;
use Illuminate\Http\Request;

class WoocrackPluginController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index() {
        return WoocrackPluginResource::collection( WoocrackPlugin::all() );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return WoocrackPluginResource
     */
    public function store( StoreWoocrackPluginsRequest $request ) {
        $woocrack_plugin = WoocrackPlugin::create( [
            'url' => $request->url,
        ] );

        return new WoocrackPluginResource( $woocrack_plugin );
    }

    public function stores( API_StoreWoocrackPluginsRequest $request ) {
        $plugin_urls = $request->input( 'plugin_urls' );

        $woocrack_plugins = array();
        $count            = 0;
        $count_updated    = 0;
        foreach ( $plugin_urls as $key => $plugin_url ) {

            $plugin_url = $plugin_url['URL'];
            $count ++;
            $plugin       = WoocrackPlugin::where( 'url', '=', $plugin_url )->get()->toArray();
            $plugin_count = \count( $plugin );
            if ( $plugin_count === 0 ) {
                $woocrack_plugins[] = WoocrackPlugin::create( [
                    'url' => $plugin_url,
                ] );
                $count_updated ++;
            }
        }

        return response()->json( $woocrack_plugins );
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show( WoocrackPlugin $id ) {
        //
        return new WoocrackPluginResource( $id );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param WoocrackPlugin $id
     *
     * @return WoocrackPluginResource
     */
    public function update( Request $request, WoocrackPlugin $id ) {
        //
        $id->update( $request->only( [ 'title', 'description' ] ) );

        return new WoocrackPluginResource( $id );
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param WoocrackPlugin $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy( WoocrackPlugin $id ) {
        //
        try {
            $id->delete();

            return response()->json( null, 204 );

        } catch ( \Exception $e ) {
            return response()->json( array( 'error' => 'not deleted' ), 204 );

        }

    }
}

resources/views/admin/woocrack_plugins/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.woocrack_plugins.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('url', trans('quickadmin.woocrack-plugins.fields.url').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('url', old('url'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('url'))
                        <p class="help-block">
                            {{ $errors->first('url') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Woocrack plugins downloads
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.download-url')</th>
                        <th>@lang('quickadmin.woocrack-plugins-downloads.fields.version')</th>
                        
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody id="woocrack-plugins-downloads">
                    @foreach(old('woocrack_plugins_downloads', []) as $index => $data)
                        @include('admin.woocrack_plugins.woocrack_plugins_downloads_row', [
                            'index' => $index
                        ])
                    @endforeach
                </tbody>
            </table>
            <a href="#" class="btn btn-success pull-right add-new">@lang('quickadmin.qa_add_new')</a>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script type="text/html" id="woocrack-plugins-downloads-template">
        @include('admin.woocrack_plugins.woocrack_plugins_downloads_row',
                [
                    'index' => '_INDEX_',
                ])
               </script > 

            <script>
        $('.add-new').click(function () {
            var tableBody = $(this).parent().find('tbody');
            var template = $('#' + tableBody.attr('id') + '-template').html();
            var lastIndex = parseInt(tableBody.find('tr').last().data('index'));
            if (isNaN(lastIndex)) {
                lastIndex = 0;
            }
            tableBody.append(template.replace(/_INDEX_/g, lastIndex + 1));
            return false;
        });
        $(document).on('click', '.remove', function () {
            var row = $(this).parentsUntil('tr').parent();
            row.remove();
            return false;
        });
        </script>
@stop

resources/views/admin/woocrack_plugins/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins.title')</h3>
    @can('woocrack_plugin_create')
        <p>
            <a href="{{ route('admin.woocrack_plugins.create') }}"
               class="btn btn-success">@lang('quickadmin.qa_add_new')</a>

        </p>
    @endcan

    @can('woocrack_plugin_delete')
        <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.woocrack_plugins.index') }}"
                   style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a>
            </li>
            |
            <li><a href="{{ route('admin.woocrack_plugins.index') }}?show_deleted=1"
                   style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a>
            </li>
        </ul>
        </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table
                class="table table-bordered table-striped ajaxTable @can('woocrack_plugin_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                <tr>
                    @can('woocrack_plugin_delete')
                        @if ( request('show_deleted') != 1 )
                            <th style="text-align:center;"><input type="checkbox" id="select-all"/></th>@endif
                    @endcan

                    <th>@lang('quickadmin.woocrack-plugins.fields.url')</th>
                    <th>@lang('quickadmin.woocrack-plugins.fields.author_url')</th>
                    @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                    @else
                        <th>&nbsp;</th>
                    @endif
                </tr>
                </thead>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        @can('woocrack_plugin_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.woocrack_plugins.mass_destroy') }}';
        @endif
        @endcan
        $(document).ready(function() {
            window.dtDefaultOptions.ajax = '{!! route('admin.woocrack_plugins.index') !!}?show_deleted={{ request('show_deleted') }}';
            window.dtDefaultOptions.columns = [
                    @can('woocrack_plugin_delete')
                    @if ( request('show_deleted') != 1 )
                {
                    data: 'massDelete', name: 'id', searchable: false, sortable: false,
                },
                    @endif
                    @endcan{
                    data: 'url', name: 'url',
                }, {data: 'author_url', name: 'author_url'},

                {data: 'actions', name: 'actions', searchable: false, sortable: false},
            ];
            processAjaxTables();
        });
    </script>
@endsection

resources/views/admin/woocrack_plugins/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.woocrack-plugins.fields.url')</th>
                            <td field-key='url'>{{ $woocrack_plugin->url }}</td>
                            <th>@lang('quickadmin.woocrack-plugins.fields.author_url')</th>
                            <td field-key='url'>{{ $woocrack_plugin->author_url }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">

                <li role="presentation" class="active"><a href="#woocrack_plugins_downloads"
                                                          aria-controls="woocrack_plugins_downloads" role="tab"
                                                          data-toggle="tab">Woocrack plugins downloads</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="woocrack_plugins_downloads">
                    <table
                        class="table table-bordered table-striped {{ count($woocrack_plugins_downloads) > 0 ? 'datatable' : '' }}">
                        <thead>
                        <tr>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.download-url')</th>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.version')</th>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.last-update')</th>
                            @if( request('show_deleted') == 1 )
                                <th>&nbsp;</th>
                            @else
                                <th>&nbsp;</th>
                            @endif
                        </tr>
                        </thead>

                        <tbody>
                        @if (count($woocrack_plugins_downloads) > 0)
                            @foreach ($woocrack_plugins_downloads as $woocrack_plugins_download)
                                <tr data-entry-id="{{ $woocrack_plugins_download->id }}">
                                    <td field-key='download_url'><a
                                            href="{{ $woocrack_plugins_download->download_url }}">{{ $woocrack_plugins_download->download_url }}</a>
                                    </td>
                                    <td field-key='version'>{{ $woocrack_plugins_download->version }}</td>
                                    <td field-key='last_update'>{{ $woocrack_plugins_download->last_update }}</td>
                                    @if( request('show_deleted') == 1 )
                                        <td>
                                            @can('woocrack_plugins_download_delete')
                                                {!! Form::open(array(
                'style' => 'display: inline-block;',
                'method' => 'POST',
                'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                'route' => ['admin.woocrack_plugins_downloads.restore', $woocrack_plugins_download->id])) !!}
                                                {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                                {!! Form::close() !!}
                                            @endcan
                                            @can('woocrack_plugins_download_delete')
                                                {!! Form::open(array(
                'style' => 'display: inline-block;',
                'method' => 'DELETE',
                'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                'route' => ['admin.woocrack_plugins_downloads.perma_del', $woocrack_plugins_download->id])) !!}
                                                {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                                {!! Form::close() !!}
                                            @endcan
                                        </td>
                                    @else
                                        <td>
                                            @can('woocrack_plugins_download_view')
                                                <a href="{{ route('admin.woocrack_plugins_downloads.show',[$woocrack_plugins_download->id]) }}"
                                                   class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                            @endcan
                                            @can('woocrack_plugins_download_edit')
                                                <a href="{{ route('admin.woocrack_plugins_downloads.edit',[$woocrack_plugins_download->id]) }}"
                                                   class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                            @endcan
                                            @can('woocrack_plugins_download_delete')
                                                {!! Form::open(array(
                                                                                        'style' => 'display: inline-block;',
                                                                                        'method' => 'DELETE',
                                                                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                                                                        'route' => ['admin.woocrack_plugins_downloads.destroy', $woocrack_plugins_download->id])) !!}
                                                {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                                {!! Form::close() !!}
                                            @endcan
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="9">@lang('quickadmin.qa_no_entries_in_table')</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.woocrack_plugins.index') }}"
               class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop

resources/views/admin/woocrack_plugins/woocrack_plugins_downloads_row.blade.php
<tr data-index="{{ $index }}">
    <td>{!! Form::text('woocrack_plugins_downloads['.$index.'][download_url]', old('woocrack_plugins_downloads['.$index.'][download_url]', isset($field) ? $field->download_url: ''), ['class' => 'form-control']) !!}</td>
<td>{!! Form::text('woocrack_plugins_downloads['.$index.'][version]', old('woocrack_plugins_downloads['.$index.'][version]', isset($field) ? $field->version: ''), ['class' => 'form-control']) !!}</td>

    <td>
        <a href="#" class="remove btn btn-xs btn-danger">@lang('quickadmin.qa_delete')</a>
    </td>
</tr>