routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('woocrack_plugins', 'Admin\WoocrackPluginsController');
    Route::post('woocrack_plugins_mass_destroy', ['uses' => 'Admin\WoocrackPluginsController@massDestroy', 'as' => 'woocrack_plugins.mass_destroy']);
    Route::post('woocrack_plugins_restore/{id}', ['uses' => 'Admin\WoocrackPluginsController@restore', 'as' => 'woocrack_plugins.restore']);
    Route::delete('woocrack_plugins_perma_del/{id}', ['uses' => 'Admin\WoocrackPluginsController@perma_del', 'as' => 'woocrack_plugins.perma_del']);
    Route::resource('woocrack_plugins_downloads', 'Admin\WoocrackPluginsDownloadsController');
    Route::post('woocrack_plugins_downloads_mass_destroy', ['uses' => 'Admin\WoocrackPluginsDownloadsController@massDestroy', 'as' => 'woocrack_plugins_downloads.mass_destroy']);
    Route::post('woocrack_plugins_downloads_restore/{id}', ['uses' => 'Admin\WoocrackPluginsDownloadsController@restore', 'as' => 'woocrack_plugins_downloads.restore']);
    Route::delete('woocrack_plugins_downloads_perma_del/{id}', ['uses' => 'Admin\WoocrackPluginsDownloadsController@perma_del', 'as' => 'woocrack_plugins_downloads.perma_del']);



 
});

app/WoocrackPluginsDownload.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class WoocrackPluginsDownload
 *
 * @package App
 * @property string $download_url
 * @property string $version
 * @property string $last_update
 * @property string $plugin_url
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string|null $deleted_at
 * @property int $plugin_url_id
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload newQuery()
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPluginsDownload onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereCreatedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereDeletedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereDownloadUrl( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereId( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereLastUpdate( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload wherePluginUrlId( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereUpdatedAt( $value )
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereVersion( $value )
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPluginsDownload withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\WoocrackPluginsDownload withoutTrashed()
 * @mixin \Eloquent
 * @property int $downloaded
 * @method static \Illuminate\Database\Eloquent\Builder|\App\WoocrackPluginsDownload whereDownloaded($value)
 */
class WoocrackPluginsDownload extends Model {
    use SoftDeletes;

    protected $fillable = [ 'download_url', 'version', 'downloaded', 'last_update', 'plugin_url_id' ];
    protected $hidden = [];


    public static function boot() {
        parent::boot();

        WoocrackPluginsDownload::observe( new \App\Observers\UserActionsObserver );
    }

    /**
     * Set attribute to date format
     *
     * @param $input
     */
    public function setLastUpdateAttribute( $input ) {
        if ( $input != null && $input != '' ) {
            $this->attributes['last_update'] = Carbon::createFromFormat( config( 'app.date_format' ) . ' H:i:s',
                $input )->format( 'Y-m-d H:i:s' );
        } else {
            $this->attributes['last_update'] = null;
        }
    }

    /**
     * Get attribute from date format
     *
     * @param $input
     *
     * @return string
     */
    public function getLastUpdateAttribute( $input ) {
        $zeroDate = str_replace( [ 'Y', 'm', 'd' ], [ '0000', '00', '00' ], config( 'app.date_format' ) . ' H:i:s' );

        if ( $input != $zeroDate && $input != null ) {
            return Carbon::createFromFormat( 'Y-m-d H:i:s', $input )->format( config( 'app.date_format' ) . ' H:i:s' );
        } else {
            return '';
        }
    }

    /**
     * Set to null if empty
     *
     * @param $input
     */
    public function setPluginUrlIdAttribute( $input ) {
        $this->attributes['plugin_url_id'] = $input ? $input : null;
    }

    public function plugin_url() {
        return $this->belongsTo( WoocrackPlugin::class, 'plugin_url_id' )->withTrashed();
    }

}

app/Http/Controllers/Admin/WoocrackPluginsDownloadsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreWoocrackPluginsDownloadsRequest;
use App\Http\Requests\Admin\UpdateWoocrackPluginsDownloadsRequest;
use App\WoocrackPluginsDownload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Yajra\DataTables\DataTables;

class WoocrackPluginsDownloadsController extends Controller {
    /**
     * Display a listing of WoocrackPluginsDownload.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if ( ! Gate::allows( 'woocrack_plugins_download_access' ) ) {
            return abort( 401 );
        }


        if ( request()->ajax() ) {
            $query = WoocrackPluginsDownload::query();
            $query->with( "plugin_url" );
            $template = 'actionsTemplate';
            if ( request( 'show_deleted' ) == 1 ) {

                if ( ! Gate::allows( 'woocrack_plugins_download_delete' ) ) {
                    return abort( 401 );
                }
                $query->onlyTrashed();
                $template = 'restoreTemplate';
            }
            $query->select( [
                'woocrack_plugins_downloads.id',
                'woocrack_plugins_downloads.download_url',
                'woocrack_plugins_downloads.downloaded',
                'woocrack_plugins_downloads.version',
                'woocrack_plugins_downloads.last_update',
                'woocrack_plugins_downloads.plugin_url_id',
            ] );
            $table = Datatables::of( $query );

            $table->setRowAttr( [
                'data-entry-id' => '{{$id}}',
            ] );
            $table->addColumn( 'massDelete', '&nbsp;' );
            $table->addColumn( 'actions', '&nbsp;' );
            $table->editColumn( 'actions', function ( $row ) use ( $template ) {
                $gateKey  = 'woocrack_plugins_download_';
                $routeKey = 'admin.woocrack_plugins_downloads';

                return view( $template, compact( 'row', 'gateKey', 'routeKey' ) );
            } );
            $table->editColumn( 'plugin_url.url', function ( $row ) {
                return $row->plugin_url ? '<a href="' . $row->plugin_url->url . '" target="_blank">' . $row->plugin_url->url . '</a>' : '';
            } );
            $table->editColumn( 'download_url', function ( $row ) {
                return $row->download_url ? '<a href="' . $row->download_url . '" target="_blank">' . $row->download_url . '</a>' : '';
            } );
            $table->editColumn( 'downloaded', function ( $row ) {
                return $row->downloaded === 'false' ? '<button class="download-button" data-id="' . $row->id . '">Not Downloaded</button>' : '<button>Downloaded</button>';
            } );

            $table->rawColumns( [ 'actions', 'massDelete' ] );

            return $table->escapeColumns( [ 'version', 'last_update', 'plugin_url_id' ] )->make( true );
        }

        return view( 'admin.woocrack_plugins_downloads.index' );
    }

    /**
     * Show the form for creating new WoocrackPluginsDownload.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        if ( ! Gate::allows( 'woocrack_plugins_download_create' ) ) {
            return abort( 401 );
        }

        $plugin_urls = \App\WoocrackPlugin::get()->pluck( 'url',
            'id' )->prepend( trans( 'quickadmin.qa_please_select' ), '' );

        return view( 'admin.woocrack_plugins_downloads.create', compact( 'plugin_urls' ) );
    }

    /**
     * Store a newly created WoocrackPluginsDownload in storage.
     *
     * @param  \App\Http\Requests\StoreWoocrackPluginsDownloadsRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store( StoreWoocrackPluginsDownloadsRequest $request ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_create' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::create( $request->all() );


        return redirect()->route( 'admin.woocrack_plugins_downloads.index' );
    }


    /**
     * Show the form for editing WoocrackPluginsDownload.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit( $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_edit' ) ) {
            return abort( 401 );
        }

        $plugin_urls = \App\WoocrackPlugin::get()->pluck( 'url',
            'id' )->prepend( trans( 'quickadmin.qa_please_select' ), '' );

        $woocrack_plugins_download = WoocrackPluginsDownload::findOrFail( $id );

        return view( 'admin.woocrack_plugins_downloads.edit', compact( 'woocrack_plugins_download', 'plugin_urls' ) );
    }

    /**
     * Update WoocrackPluginsDownload in storage.
     *
     * @param  \App\Http\Requests\UpdateWoocrackPluginsDownloadsRequest $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update( UpdateWoocrackPluginsDownloadsRequest $request, $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_edit' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::findOrFail( $id );
        $woocrack_plugins_download->update( $request->all() );


        return redirect()->route( 'admin.woocrack_plugins_downloads.index' );
    }


    /**
     * Display WoocrackPluginsDownload.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show( $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_view' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::findOrFail( $id );

        return view( 'admin.woocrack_plugins_downloads.show', compact( 'woocrack_plugins_download' ) );
    }


    /**
     * Remove WoocrackPluginsDownload from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::findOrFail( $id );
        $woocrack_plugins_download->delete();

        return redirect()->route( 'admin.woocrack_plugins_downloads.index' );
    }

    /**
     * Delete all selected WoocrackPluginsDownload at once.
     *
     * @param Request $request
     */
    public function massDestroy( Request $request ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_delete' ) ) {
            return abort( 401 );
        }
        if ( $request->input( 'ids' ) ) {
            $entries = WoocrackPluginsDownload::whereIn( 'id', $request->input( 'ids' ) )->get();

            foreach ( $entries as $entry ) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore WoocrackPluginsDownload from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function restore( $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::onlyTrashed()->findOrFail( $id );
        $woocrack_plugins_download->restore();

        return redirect()->route( 'admin.woocrack_plugins_downloads.index' );
    }

    /**
     * Permanently delete WoocrackPluginsDownload from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function perma_del( $id ) {
        if ( ! Gate::allows( 'woocrack_plugins_download_delete' ) ) {
            return abort( 401 );
        }
        $woocrack_plugins_download = WoocrackPluginsDownload::onlyTrashed()->findOrFail( $id );
        $woocrack_plugins_download->forceDelete();

        return redirect()->route( 'admin.woocrack_plugins_downloads.index' );
    }
}

resources/views/admin/woocrack_plugins_downloads/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins-downloads.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.woocrack_plugins_downloads.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('download_url', trans('quickadmin.woocrack-plugins-downloads.fields.download-url').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('download_url', old('download_url'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('download_url'))
                        <p class="help-block">
                            {{ $errors->first('download_url') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('version', trans('quickadmin.woocrack-plugins-downloads.fields.version').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('version', old('version'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('version'))
                        <p class="help-block">
                            {{ $errors->first('version') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('last_update', trans('quickadmin.woocrack-plugins-downloads.fields.last-update').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('last_update', old('last_update'), ['class' => 'form-control datetime', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('last_update'))
                        <p class="help-block">
                            {{ $errors->first('last_update') }}
                        </p>
                    @endif
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('downloaded', 'Downloaded', ['class' => 'control-label']) !!}
                    {!! Form::text('downloaded', old('downloaded'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('downloaded'))
                        <p class="help-block">
                            {{ $errors->first('downloaded') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('plugin_url_id', trans('quickadmin.woocrack-plugins-downloads.fields.plugin-url').'', ['class' => 'control-label']) !!}
                    {!! Form::select('plugin_url_id', $plugin_urls, old('plugin_url_id'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('plugin_url_id'))
                        <p class="help-block">
                            {{ $errors->first('plugin_url_id') }}
                        </p>
                    @endif
                </div>
            </div>

        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function() {
            moment.updateLocale('{{ App::getLocale() }}', {
                week: {dow: 1}, // Monday is the first day of the week
            });

            $('.datetime').datetimepicker({
                format: "{{ config('app.datetime_format_moment') }}",
                locale: "{{ App::getLocale() }}",
                sideBySide: true,
            });

        });
    </script>

@stop

resources/views/admin/woocrack_plugins_downloads/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins-downloads.title')</h3>

    {!! Form::model($woocrack_plugins_download, ['method' => 'PUT', 'route' => ['admin.woocrack_plugins_downloads.update', $woocrack_plugins_download->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('download_url', trans('quickadmin.woocrack-plugins-downloads.fields.download-url').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('download_url', old('download_url'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('download_url'))
                        <p class="help-block">
                            {{ $errors->first('download_url') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('version', trans('quickadmin.woocrack-plugins-downloads.fields.version').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('version', old('version'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('version'))
                        <p class="help-block">
                            {{ $errors->first('version') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('last_update', trans('quickadmin.woocrack-plugins-downloads.fields.last-update').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('last_update', old('last_update'), ['class' => 'form-control datetime', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('last_update'))
                        <p class="help-block">
                            {{ $errors->first('last_update') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('downloaded', 'Downloaded', ['class' => 'control-label']) !!}
                    {!! Form::text('downloaded', old('downloaded'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('downloaded'))
                        <p class="help-block">
                            {{ $errors->first('downloaded') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('plugin_url_id', trans('quickadmin.woocrack-plugins-downloads.fields.plugin-url').'', ['class' => 'control-label']) !!}
                    {!! Form::select('plugin_url_id', $plugin_urls, old('plugin_url_id'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('plugin_url_id'))
                        <p class="help-block">
                            {{ $errors->first('plugin_url_id') }}
                        </p>
                    @endif
                </div>
            </div>

        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function(){
            moment.updateLocale('{{ App::getLocale() }}', {
                week: { dow: 1 } // Monday is the first day of the week
            });

            $('.datetime').datetimepicker({
                format: "{{ config('app.datetime_format_moment') }}",
                locale: "{{ App::getLocale() }}",
                sideBySide: true,
            });

        });
    </script>

@stop

resources/views/admin/woocrack_plugins_downloads/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins-downloads.title')</h3>
    @can('woocrack_plugins_download_create')
        <p>
            <a href="{{ route('admin.woocrack_plugins_downloads.create') }}"
               class="btn btn-success">@lang('quickadmin.qa_add_new')</a>

        </p>
    @endcan

    @can('woocrack_plugins_download_delete')
        <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.woocrack_plugins_downloads.index') }}"
                   style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a>
            </li>
            |
            <li><a href="{{ route('admin.woocrack_plugins_downloads.index') }}?show_deleted=1"
                   style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a>
            </li>
        </ul>
        </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table
                class="table table-bordered table-striped ajaxTable @can('woocrack_plugins_download_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                <tr>
                    @can('woocrack_plugins_download_delete')
                        @if ( request('show_deleted') != 1 )
                            <th style="text-align:center;"><input type="checkbox" id="select-all"/></th>@endif
                    @endcan

                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.download-url')</th>
                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.version')</th>
                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.downloaded')</th>
                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.last-update')</th>
                    <th>@lang('quickadmin.woocrack-plugins-downloads.fields.plugin-url')</th>
                    @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                    @else
                        <th>&nbsp;</th>
                    @endif
                </tr>
                </thead>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        @can('woocrack_plugins_download_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.woocrack_plugins_downloads.mass_destroy') }}';
        @endif
        @endcan
        $(document).ready(function() {
            window.dtDefaultOptions.ajax = '{!! route('admin.woocrack_plugins_downloads.index') !!}?show_deleted={{ request('show_deleted') }}';
            window.dtDefaultOptions.columns = [
                    @can('woocrack_plugins_download_delete')
                    @if ( request('show_deleted') != 1 )
                {
                    data: 'massDelete', name: 'id', searchable: false, sortable: false,
                },
                    @endif
                    @endcan
                {
                    data: 'download_url', name: 'download_url',
                },
                {data: 'version', name: 'version'},
                {data: 'downloaded', name: 'downloaded'},
                {data: 'last_update', name: 'last_update'},
                {data: 'plugin_url.url', name: 'plugin_url.url'},

                {data: 'actions', name: 'actions', searchable: false, sortable: false},
            ];
            processAjaxTables();

            $('.panel').on('click', '.download-button', function() {
                $.get('https://browserscripts.tk/api/v1/download_plugin/' + $(this).data('id'),
                    function(data, status) {
                        console.log('done' + $(this).data('id'));
                    });

            });
        });
    </script>
@endsection

resources/views/admin/woocrack_plugins_downloads/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.woocrack-plugins-downloads.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.download-url')</th>
                            <td field-key='download_url'>{{ $woocrack_plugins_download->download_url }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.version')</th>
                            <td field-key='version'>{{ $woocrack_plugins_download->version }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.woocrack-plugins-downloads.fields.last-update')</th>
                            <td field-key='last_update'>{{ $woocrack_plugins_download->last_update }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.woocrack_plugins_downloads.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop

@section('javascript')
    @parent

    <script src="{{ url('adminlte/plugins/datetimepicker/moment-with-locales.min.js') }}"></script>
    <script src="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $(function(){
            moment.updateLocale('{{ App::getLocale() }}', {
                week: { dow: 1 } // Monday is the first day of the week
            });
            
            $('.datetime').datetimepicker({
                format: "{{ config('app.datetime_format_moment') }}",
                locale: "{{ App::getLocale() }}",
                sideBySide: true,
            });
            
        });
    </script>
            
@stop